import {apiFetch as fetch} from './api';
import React, {useEffect,useState} from 'react';
import './App.css';
import Report from './Report';
import ReviewTools from './ReviewTools';
import GoogleLogin from './GoogleLogin';
const API=import.meta.env.VITE_API_URL??(import.meta.env.PROD?'':'http://127.0.0.1:8000');
export default function App(){
 const [token,setToken]=useState('cookie-session'); const [user,setUser]=useState(null); const [tab,setTab]=useState('dashboard'); const [scans,setScans]=useState([]); const [auth,setAuth]=useState('login'); const [form,setForm]=useState({name:'',email:'',password:''}); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(false);
 const headers=()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
 useEffect(()=>{if(token){fetch(`${API}/api/v9/me`,{headers:headers()}).then(r=>r.json()).then(d=>{if(d.success){setUser(d.user);loadScans()}else logout()}).catch(logout)}},[token]);
 async function loadScans(){const r=await fetch(`${API}/api/v9/scans`,{headers:headers()});const d=await r.json();if(d.success)setScans(d.scans)}
 function logout(){if(token)fetch(`${API}/api/v13/logout`,{method:'POST',headers:headers()}).catch(()=>{});localStorage.removeItem('cg_token');setToken('');setUser(null);setScans([])}
 async function submit(e){e.preventDefault();setLoading(true);setMsg('');const endpoint=auth==='login'?'/api/v9/auth/login':'/api/v9/auth/register';try{const r=await fetch(API+endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!d.success)throw Error(d.error||'Authentication failed');localStorage.setItem('cg_token',d.token);setToken(d.token);setUser(d.user)}catch(x){setMsg(x.message)}finally{setLoading(false)}}
 if(!user)return <div className="auth"><div className="auth-card"><div className="logo">CG<span>AI</span></div><p className="eyebrow">CODEGUARD CLOUD · V14</p><h1>{auth==='login'?'Welcome back.':'Create your security workspace.'}</h1><p className="muted">Persistent security reports, projects and scan history.</p>{auth==='register'&&<input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button onClick={submit} disabled={loading}>{loading?'PLEASE WAIT...':auth==='login'?'SIGN IN':'CREATE ACCOUNT'}</button>{msg&&<div className="error">{msg}</div>}<GoogleLogin linkPassword={form.password} onLogin={d=>{localStorage.setItem('cg_token','cookie-session');setToken('cookie-session');setUser(d.user)}}/><p className="switch" onClick={()=>{setAuth(auth==='login'?'register':'login');setMsg('')}}>{auth==='login'?'New to CodeGuard? Create an account':'Already have an account? Sign in'}</p></div></div>;
 return <div className="shell"><aside><div className="brand">CG<span>AI</span></div><div className="side-title">CODEGUARD CLOUD</div><button className={tab==='dashboard'?'nav active':'nav'} onClick={()=>setTab('dashboard')}>⌂ Dashboard</button><button className={tab==='history'?'nav active':'nav'} onClick={()=>setTab('history')}>◷ Scan History</button><button className={tab==='scan'?'nav active':'nav'} onClick={()=>setTab('scan')}>＋ New Scan</button><button className={tab==='pr'?'nav active':'nav'} onClick={()=>setTab('pr')}>⑂ PR Review</button><button className={tab==='gate'?'nav active':'nav'} onClick={()=>setTab('gate')}>✓ CI/CD Gate</button><div className="profile"><b>{user.name}</b><span>{user.email}</span><button onClick={logout}>Sign out</button></div></aside><main><header><div><p className="eyebrow">SECURITY OPERATIONS</p><h2>{tab==='dashboard'?'Security Dashboard':tab==='history'?'Scan History':tab==='pr'?'Pull Request Review':tab==='gate'?'CI/CD Security Gate':'New Security Scan'}</h2></div><div className="pill">● CODEGUARD WORKSPACE</div></header>{tab==='dashboard'?<Dashboard scans={scans} onHistory={()=>setTab('history')} onScan={()=>setTab('scan')}/>:tab==='history'?<History scans={scans} token={token}/>:tab==='pr'||tab==='gate'?<ReviewTools key={tab} mode={tab} token={token} onSaved={loadScans}/>:<NewScan token={token} onDone={async()=>{await loadScans();setTab('history')}}/>}</main></div>
}
export function Dashboard({scans,onHistory,onScan}){const total=scans.length;const avg=total?Math.round(scans.reduce((a,x)=>a+(x.score||0),0)/total):0;const passed=scans.filter(x=>x.status==='PASS').length;return <><section className="hero"><div><p className="eyebrow">V14 · PERSISTENT SECURITY INTELLIGENCE</p><h1>One place for every security scan.</h1><p className="muted">CodeGuard Cloud stores your scan history so you can track security work across projects instead of losing reports in terminal windows.</p></div><button onClick={onScan}>NEW SCAN →</button></section><section className="cards"><Card n={total} l="TOTAL SCANS"/><Card n={avg||'—'} l="AVERAGE SCORE"/><Card n={passed} l="PASSED GATES"/><Card n={total-passed} l="NEEDS REVIEW"/></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">RECENT ACTIVITY</p><h3>Latest security scans</h3></div><button className="ghost" onClick={onHistory}>See all</button></div>{scans.length?<table><thead><tr><th>Target</th><th>Type</th><th>Score</th><th>Status</th><th>Time</th></tr></thead><tbody>{scans.slice(0,8).map(s=><tr key={s.id}><td>{s.target}</td><td>{s.scan_type}</td><td>{s.score}/100</td><td><span className={s.status==='PASS'?'pass':'review'}>{s.status}</span></td><td>{new Date(s.created_at).toLocaleString()}</td></tr>)}</tbody></table>:<div className="empty">No saved scans yet. Click <b>New Scan</b> to start your first analysis.</div>}</section></>}
function Card({n,l}){return <div className="stat"><strong>{n}</strong><span>{l}</span></div>}
export function History({scans,token}){const [report,setReport]=useState(null);const [error,setError]=useState('');async function open(id){setError('');try{const r=await fetch(`${API}/api/v9/scans/${id}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw Error(d.detail||'Could not load report');setReport({...d.scan.result,target:d.scan.target,created_at:d.scan.created_at,scan_id:d.scan.id})}catch(e){setError(e.message)}}return <section className="panel"><p className="eyebrow">PERSISTENT REPORTS</p><h3>All scans</h3>{error&&<div className="error">{error}</div>}{report&&<><button className="ghost" onClick={()=>setReport(null)}>Close report</button><Report result={report} token={token}/></>}{scans.length?<div className="history">{scans.map(s=><div className="scan-row" key={s.id}><div><button className="ghost" onClick={()=>open(s.id)}>View report: {s.target}</button><span>{s.scan_type} · {new Date(s.created_at).toLocaleString()}</span></div><strong>{s.score}/100</strong><em className={s.status==='PASS'?'pass':'review'}>{s.status}</em></div>)}</div>:<div className="empty">Your scan history is empty.</div>}</section>}
export function NewScan({token,onDone}){const [mode,setMode]=useState('github');const [url,setUrl]=useState('');const [file,setFile]=useState(null);const [result,setResult]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function run(){setBusy(true);setError('');setResult(null);try{let r,d;if(mode==='github'){if(!url.trim())throw Error('Enter a GitHub repository URL.');r=await fetch(`${API}/api/v9/scan/github`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({url:url.trim()})})}else{if(!file)throw Error('Choose a ZIP project first.');const f=new FormData();f.append('file',file);r=await fetch(`${API}/api/v9/scan/zip`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:f})}d=await r.json();if(!r.ok||d.success===false)throw Error(d.error||d.detail||'Scan failed.');setResult({...d,target:mode==='github'?url:file.name})}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="scan-page"><div className="scan-intro"><p className="eyebrow">FAST SECURITY ANALYSIS</p><h1>Start a new scan.</h1><p className="muted">Scan a public GitHub repository or upload a project ZIP. Every completed scan is automatically saved to your V14 history.</p></div><div className="scan-tabs"><button className={mode==='github'?'selected':''} onClick={()=>setMode('github')}>🔗 GitHub Repository</button><button className={mode==='zip'?'selected':''} onClick={()=>setMode('zip')}>📦 Upload Project ZIP</button></div>{mode==='github'?<div className="scan-box"><label>GitHub Repository URL</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://github.com/username/project"/><p>Public repositories only. CodeGuard will download and analyze supported source files.</p></div>:<div className="scan-box"><label>Project ZIP</label><label className="file-drop"><input type="file" accept=".zip" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>{file?file.name:'Choose a .zip project archive'}</b><span>{file?'Ready to scan':'Maximum 50 MB'}</span></label></div>}<button className="run-scan" disabled={busy} onClick={run}>{busy?'RUNNING FAST ANALYSIS...':'RUN SECURITY SCAN →'}</button>{error&&<div className="error">{error}</div>}{result&&<div className="scan-result"><div><p className="eyebrow">SCAN COMPLETE</p><h2>{result.security_score??result.score??0}/100</h2><p>{result.message||'Security analysis completed and saved to Scan History.'}</p></div><div className="result-actions"><button onClick={()=>onDone()}>VIEW SCAN HISTORY</button><button className="ghost" onClick={()=>setResult(null)}>NEW SCAN</button></div></div>}{result&&<Report result={result} token={token}/>}</section>}
