import {apiFetch as fetch} from './api';
import React,{useState} from 'react';
const API=import.meta.env.VITE_API_URL??(import.meta.env.PROD?'':'http://127.0.0.1:8000');
function save(name,content){const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function FixPreview({finding,index,scanId,token}){
 const [open,setOpen]=useState(false),[automatic,setAutomatic]=useState(false),[sourceLoading,setSourceLoading]=useState(false),[sourceMessage,setSourceMessage]=useState(''),[code,setCode]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null);
 async function loadSource(){if(open){setOpen(false);return}setOpen(true);setSourceLoading(true);setConsent(false);setError('');try{const r=await fetch(`${API}/api/v11/scans/${scanId}/source/${index}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw Error(d.detail||'Could not load source');setAutomatic(d.available);setCode(d.code||'');setSourceMessage(d.available?'Source loaded automatically from your scanned ZIP.':d.message)}catch(e){setError(e.message)}finally{setSourceLoading(false)}}
 async function generate(){setBusy(true);setError('');setResult(null);try{const r=await fetch(`${API}/api/v11/fix`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({scan_id:scanId,finding_index:index,code,consent})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.error||d.detail||'Fix request failed');setResult(d)}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(!finding.file?.toLowerCase().endsWith('.py'))return <small>AI fix preview supports Python files.</small>;
 return <div className="fix-workspace"><button className="ghost" onClick={loadSource}>{open?'Close fix workspace':'Generate Fix'}</button>{open&&<><p className="muted">{sourceLoading?'Loading matching source…':sourceMessage} File: {finding.file}.</p><textarea readOnly={automatic} aria-label="Python source for fix" value={code} onChange={e=>{setCode(e.target.value);setResult(null);setConsent(false)}} placeholder="Paste the full Python source here…"/><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Send this source file and finding to Groq for AI remediation. Remove credentials and private data first.</label><button className="ghost" disabled={busy||sourceLoading||!consent||!code.trim()||!scanId} onClick={generate}>{busy?'Generating preview…':'Generate AI preview'}</button>{error&&<p className="error">{error}</p>}{result&&<><h4>{result.fix.summary}</h4><p className="muted">{result.validation.syntax_valid?'Python syntax valid':'Python syntax failed'} · {result.validation.changed?'Code changed':'No changes'} · {result.validation.target_rule_cleared?'Selected rule cleared by static checks':'Selected rule still needs review'}</p><p className="muted">{result.validation.note}</p><div className="code-compare"><div><h4>Original</h4><pre>{result.original_code}</pre></div><div><h4>Suggested replacement</h4><pre>{result.fix.fixed_code}</pre></div></div><h4>Unified diff</h4><pre>{result.validation.patch||'No patch generated.'}</pre>{result.validation.syntax_valid&&result.validation.changed&&<div className="exports"><button className="ghost" onClick={()=>save('CodeGuard_fix.patch',result.validation.patch)}>Download patch</button><button className="ghost" onClick={()=>save((finding.file.split('/').pop()||'source.py').replace('.py','.fixed.py'),result.fix.fixed_code)}>Download fixed Python</button></div>}<p className="muted">Review the suggestion and test it in your project before applying it.</p></>}</>}</div>
}
