import React, {useState} from 'react';
import FixPreview from './FixPreview';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function download(name,type,content){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function Report({result,token}){
 const [severity,setSeverity]=useState('ALL');const [query,setQuery]=useState('');
 const findings=result.findings||result.issues||[];const errors=result.syntax_errors||[];
 const visible=findings.filter(f=>(severity==='ALL'||f.severity===severity)&&`${f.file} ${f.message} ${f.category} ${f.rule_id}`.toLowerCase().includes(query.toLowerCase()));
 const coverage=result.coverage||'Python AST security rules. Files over 750 KB and files beyond the 500-file limit are excluded.';
 const exportHtml=()=>{const rows=findings.map(f=>`<tr><td>${escape(f.severity)}</td><td>${escape(f.file)}:${escape(f.line)}</td><td>${escape(f.rule_id)}</td><td>${escape(f.message)}</td><td>${escape(f.recommendation)}</td></tr>`).join('');download('CodeGuard_Report.html','text/html',`<!doctype html><html lang="en"><meta charset="utf-8"><title>CodeGuard Security Report</title><style>body{font:16px system-ui;margin:40px;color:#17243b}table{width:100%;border-collapse:collapse}td,th{padding:12px;border:1px solid #ddd;text-align:left;overflow-wrap:anywhere}@media print{body{margin:0}}</style><h1>CodeGuard AI Security Report</h1><p>Target: ${escape(result.target||result.filename||result.repository?.url||'Project')}</p><p>Score: ${escape(result.security_score??result.score??0)}/100 · ${escape(result.status||'COMPLETED')}</p><p>${escape(coverage)}</p><p>Static findings require human review; a passing scan is not a guarantee of security.</p><h2>Findings (${findings.length})</h2><table><thead><tr><th>Severity</th><th>Location</th><th>Rule</th><th>Explanation</th><th>Recommendation</th></tr></thead><tbody>${rows}</tbody></table><h2>Syntax errors</h2>${errors.map(e=>`<p>${escape(e.file)}: ${escape(e.message)}</p>`).join('')||'<p>None reported.</p>'}</html>`)};
 return <section className="panel report"><div className="panel-head"><div><p className="eyebrow">V11 · FINDINGS EXPLORER</p><h3>Security report</h3><p className="muted">{result.target||result.filename||result.repository?.url}</p></div><div className="exports"><button className="ghost" onClick={()=>download('CodeGuard_Report.json','application/json',JSON.stringify(result,null,2))}>Download JSON</button><button className="ghost" onClick={exportHtml}>Download HTML / Print PDF</button></div></div><p className="muted">{result.files_scanned??'—'} files · {result.lines_scanned??result.lines_analyzed??'—'} lines · {findings.length} findings</p><div className="severity-summary">{['CRITICAL','HIGH','MEDIUM','LOW'].map(s=><button key={s} className={'severity '+s.toLowerCase()} onClick={()=>setSeverity(s)}>{s} {findings.filter(f=>f.severity===s).length}</button>)}</div><div className="report-filters"><label>Severity <select value={severity} onChange={e=>setSeverity(e.target.value)}>{['ALL','CRITICAL','HIGH','MEDIUM','LOW'].map(s=><option key={s}>{s}</option>)}</select></label><input aria-label="Search findings" placeholder="Search file, rule, or finding…" value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="muted">Showing {visible.length} of {findings.length}</p>{visible.map((f,i)=><article className="finding" key={`${f.file}-${f.line}-${f.rule_id}-${i}`}><span className={'severity '+String(f.severity).toLowerCase()}>{f.severity}</span><code>{f.file||'Source'}:{f.line||'—'}</code><h4>{f.category||'Security finding'}</h4><p>{f.message}</p><p className="muted"><b>Recommended action: </b>{f.recommendation||'Review this pattern and validate the inputs involved.'}</p><small>{f.rule_id||'Unspecified rule'}{f.pr_status?' · '+f.pr_status:''}</small><FixPreview finding={f} index={findings.indexOf(f)} scanId={result.scan_id} token={token}/></article>)}{!visible.length&&<p className="empty">{findings.length?'No findings match these filters.':'No findings detected by the current rules. Review coverage and syntax errors below.'}</p>}{errors.length>0&&<div className="error"><b>Files that could not be parsed</b>{errors.map((e,i)=><p key={i}>{e.file}: {e.message}</p>)}</div>}<p className="muted">Coverage: {coverage} Static findings require human review; a passing scan is not a guarantee of security.</p></section>
}
