import {apiFetch as fetch} from './api';
import React,{useState} from 'react';
import Report from './Report';
const API=import.meta.env.VITE_API_URL??(import.meta.env.PROD?'':'http://127.0.0.1:8000');
export default function ReviewTools({mode,token,onSaved}){
 const [url,setUrl]=useState(''),[file,setFile]=useState(null),[threshold,setThreshold]=useState(80),[high,setHigh]=useState(0),[critical,setCritical]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null);
 async function run(){setBusy(true);setError('');setResult(null);try{let response;if(mode==='pr'){response=await fetch(API+'/api/v12/pr-review',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({url})})}else{if(!file)throw Error('Choose a ZIP first.');const body=new FormData();body.append('file',file);body.append('threshold',threshold);body.append('max_high',high);body.append('max_critical',critical);response=await fetch(API+'/api/v12/gate',{method:'POST',headers:{Authorization:`Bearer ${token}`},body})}const data=await response.json();if(!response.ok||data.success===false)throw Error(typeof data.detail==='string'?data.detail:data.error||'Review failed; check inputs and backend.');setResult({...data,target:mode==='pr'?url:file.name});onSaved?.()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="scan-page"><p className="eyebrow">V12 · DEVELOPER WORKFLOWS</p><h1>{mode==='pr'?'Review a pull request.':'Check your security gate.'}</h1><p className="muted">{mode==='pr'?'Analyze Python files in a public GitHub pull request. Review findings on added lines and existing findings. No GitHub comments or changes are posted.':'Upload a source ZIP and choose the score and severity limits your build must meet. Results are saved to your scan history.'}</p><div className="scan-box">{mode==='pr'?<><label>Public GitHub pull-request URL</label><input aria-label="Pull request URL" placeholder="https://github.com/owner/repo/pull/123" value={url} onChange={e=>setUrl(e.target.value)}/></>:<><label>Project ZIP<input type="file" accept=".zip" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="report-filters"><label>Minimum score<input aria-label="Minimum score" type="number" min="0" max="100" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><label>Maximum high findings<input type="number" min="0" value={high} onChange={e=>setHigh(e.target.value)}/></label><label>Maximum critical findings<input type="number" min="0" value={critical} onChange={e=>setCritical(e.target.value)}/></label></div></>}</div><button className="run-scan" disabled={busy} onClick={run}>{busy?'Analyzing…':mode==='pr'?'REVIEW PULL REQUEST':'RUN SECURITY GATE'}</button>{error&&<p className="error">{error}</p>}{result&&<><div className="panel"><h2>{result.status} · {result.security_score??result.score}/100</h2>{mode==='pr'?<><h3>{result.pull_request?.title}</h3><p>{result.files_changed} changed files · {result.python_files_changed} Python files</p><p>{result.summary?.introduced} findings on added lines · {result.summary?.existing} existing findings</p><details><summary>Changed files</summary>{result.files?.map(f=><p key={f.file}>{f.file} · +{f.additions} / −{f.deletions}{f.error&&' · '+f.error}</p>)}</details></>:<p>{result.message} Minimum score: {result.threshold}, high limit: {result.max_high_allowed}, critical limit: {result.max_critical_allowed}.</p>}</div><Report result={result} token={token}/></>}{mode==='gate'&&<div className="panel"><h3>Run in CI/CD</h3><p className="muted">Use the included CLI on a project source ZIP. Exit code 0 passes, 1 blocks the build, and 2 indicates an input/tool error. See README_V12.md for the GitHub Actions example.</p><pre>python backend/ci_gate_cli.py project.zip --threshold 80 --max-high 0 --max-critical 0 --json</pre></div>}</section>
}
